# Generated by Django 4.1 on 2022-11-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmatchs',
            name='stadium',
            field=models.CharField(default=14.041666666666666, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allmatchs',
            name='tournament',
            field=models.CharField(default=14.041666666666666, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allmatchs',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamoa_1', to='main.team'),
        ),
        migrations.AlterField(
            model_name='allmatchs',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamoa_2', to='main.team'),
        ),
    ]
