# Generated by Django 4.1 on 2022-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_allmatchs_stadium_allmatchs_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='playervideos/'),
        ),
    ]
